# TEST 7

name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  sonarqube-scan:
    uses: bhassan-techtrend/poc-for-jenkins-migration/.github/workflows/sonarqube.yml@main
    secrets:
      sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      sonar_project_key: ${{ secrets.SONAR_PROJECT_KEY }}

  call-owasp-scan:
    uses: bhassan-techtrend/poc-for-jenkins-migration/.github/workflows/owasp-dependency-check.yml@main  # Calls the reusable workflow
    with:
      project_name: "MyProjectName"  # Passes the project name as input
