# TEST 2

name: CI Pipeline for sonarqube using submodules

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  sonarqube-scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repositroy with modules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: reuse submodule workflow 
        run: |
          echo "Running sonarqube and owasp workflows from submodules"
          bash .github/submodules/shared-library-2/.github/workflows/sonarqube.yml
        
        # with:
        #   sonar_dir: src/Build
        # env:
        #   sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
        #   sonar_token: ${{ secrets.SONAR_TOKEN }}





    # uses: bhassan-techtrend/poc-for-jenkins-migration/.github/workflows/sonarqube.yml@main
    # with:
    #   sonar_dir: src/Build
    # secrets:
    #   sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
    #   sonar_token: ${{ secrets.SONAR_TOKEN }}

  # sonarqube-scan-dir-two:
  #   uses: bhassan-techtrend/poc-for-jenkins-migration/.github/workflows/sonarqube.yml@main
  #   with:
  #     sonar_dir: src/Libraries
  #   secrets:
  #     sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
  #     sonar_token: ${{ secrets.SONAR_TOKEN }}

  # call-owasp-scan:
  #   uses: bhassan-techtrend/poc-for-jenkins-migration/.github/workflows/owasp-dependency-check.yml@main  # Calls the reusable workflow
  #   with:
  #     project_name: "MyProjectName"  # Passes the project name as input
