# TEST 5

name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  sonarqube-scan:
    uses: bhassan-techtrend/poc-for-jenkins-migration/.github/workflows/sonarqube.yml@main
    secrets:
      sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
